//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractSchedulerQueue
    {
        public System.Guid Id { get; set; }
        public string ExtractId { get; set; }
        public string SurveyId { get; set; }
        public string ConsoriumGroupId { get; set; }
        public string EntityType { get; set; }
        public string EntityId { get; set; }
        public string MemberId { get; set; }
        public string DimensionSchema { get; set; }
        public string Dimension { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string Status { get; set; }
        public string KEY_001 { get; set; }
        public string DATA_001 { get; set; }
        public string DATA_002 { get; set; }
        public string DATA_003 { get; set; }
        public string DATA_004 { get; set; }
        public string DATA_005 { get; set; }
        public string DATA_006 { get; set; }
        public string DATA_007 { get; set; }
        public string DATA_008 { get; set; }
        public string DATA_009 { get; set; }
        public string DATA_010 { get; set; }
    }
}
