//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIProcessStepInstance_Snapshots
    {
        public System.Guid Id { get; set; }
        public string CurrentStepInstanceId { get; set; }
        public string PreceedingStepId { get; set; }
        public string PreceedingStepInstanceId { get; set; }
        public string UserToken { get; set; }
        public string InstanceCaseId { get; set; }
        public string InstanceEntityType { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public string Outcome { get; set; }
        public string Param_0001 { get; set; }
        public string Param_0002 { get; set; }
        public string Param_0003 { get; set; }
        public string Param_0004 { get; set; }
        public string Param_0005 { get; set; }
        public string Param_0006 { get; set; }
        public string Param_0007 { get; set; }
        public string Param_0008 { get; set; }
        public string Param_0009 { get; set; }
        public string Param_0010 { get; set; }
    }
}
