//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProfile
    {
        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public int EmisCode { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string RefName { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Telephone { get; set; }
        public Nullable<short> LocationUID { get; set; }
        public Nullable<int> EIDistrict { get; set; }
        public string DistrictName { get; set; }
        public string EICircuit { get; set; }
        public string CircuitName { get; set; }
        public bool IsActive { get; set; }
        public bool IsProfilePublic { get; set; }
        public Nullable<int> Proxy { get; set; }
        public Nullable<int> Proxy1 { get; set; }
        public Nullable<int> Rank { get; set; }
        public string RankName { get; set; }
        public int Level { get; set; }
        public string Position { get; set; }
        public Nullable<int> PositionCode { get; set; }
        public Nullable<int> Directorate { get; set; }
        public string DirectorateCode { get; set; }
        public string DirectorateName { get; set; }
        public string GIS_Long { get; set; }
        public string GIS_Lat { get; set; }
        public string GIS_ERROR { get; set; }
        public string GISSource { get; set; }
        public string Sector { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string DoE_Status { get; set; }
        public string Phase_DoE { get; set; }
        public string meta { get; set; }
        public Nullable<int> PhaseCD { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
