//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Lock
    {
        public System.Guid Id { get; set; }
        public string EntityId { get; set; }
        public string EntityType { get; set; }
        public string LockedBy { get; set; }
        public System.DateTime LockedFrom { get; set; }
        public Nullable<System.DateTime> ReleasedAt { get; set; }
        public string ReleasedBy { get; set; }
        public string IsLocked { get; set; }
    }
}
