//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRequest
    {
        public int Id { get; set; }
        public Nullable<System.Guid> RowGUID { get; set; }
        public string ReqId { get; set; }
        public string InvBarCode { get; set; }
        public int Quantity { get; set; }
        public int CategoryCD { get; set; }
        public string EntityId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal TotalPrice { get; set; }
    }
}
