//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalSnE : DbContext
    {
        public PortalSnE()
            : base("name=PortalSnE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WIOutcome_Lookup> WIOutcome_Lookup { get; set; }
        public virtual DbSet<WIProcess> WIProcesses { get; set; }
        public virtual DbSet<WIProcessStep> WIProcessSteps { get; set; }
        public virtual DbSet<WIProcessStepInstance> WIProcessStepInstances { get; set; }
        public virtual DbSet<C_Error> C_Error { get; set; }
        public virtual DbSet<C_WILock> C_WILock { get; set; }
        public virtual DbSet<WIProcessInstance> WIProcessInstances { get; set; }
    }
}
