//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PortalAuth : DbContext
    {
        public PortalAuth()
            : base("name=PortalAuth")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Directorate> Directorates { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<AspNetProfile> AspNetProfiles { get; set; }
        public virtual DbSet<vwMembersPerRole> vwMembersPerRoles { get; set; }
        public virtual DbSet<vwMailbox> vwMailboxes { get; set; }
        public virtual DbSet<vwAccountSetting> vwAccountSettings { get; set; }
        public virtual DbSet<vwAddressDetail> vwAddressDetails { get; set; }
        public virtual DbSet<vwContact> vwContacts { get; set; }
        public virtual DbSet<vwPersonalDetail> vwPersonalDetails { get; set; }
        public virtual DbSet<vwPositionDetail> vwPositionDetails { get; set; }
    
        public virtual ObjectResult<spMailbox_Result> spMailbox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMailbox_Result>("spMailbox");
        }
    }
}
