//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Inventory
    {
        public System.Guid Id { get; set; }
        public int EmisCode { get; set; }
        public string BookName { get; set; }
        public string ISBN { get; set; }
        public string Publisher { get; set; }
        public string Author { get; set; }
        public string Language { get; set; }
        public string Category { get; set; }
        public int CategoryCD { get; set; }
        public int Sub_Code { get; set; }
        public string SubjectName { get; set; }
        public string Key { get; set; }
        public int Grade { get; set; }
        public int Class_Enr { get; set; }
        public int Subj_Enr { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int Teachers { get; set; }
        public string TLR { get; set; }
        public int IsBookmarked { get; set; }
        public Nullable<decimal> GradeBudget { get; set; }
        public string BookYear { get; set; }
    }
}
