//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RequisitionEntityTotalPrice
    {
        public string ReqId { get; set; }
        public string EntityId { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
