//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFProcessInstance
    {
        public int id { get; set; }
        public System.Guid InstanceId { get; set; }
        public string FlowId { get; set; }
        public string EntityId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string ExceptedCompletionDateVariable { get; set; }
        public string ExceptedCompletionDateSubVariable { get; set; }
        public Nullable<System.DateTime> ExpectedCompletionDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastEditedBy { get; set; }
        public string Outcome { get; set; }
        public string State { get; set; }
    }
}
