//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIProcessInstance
    {
        public int id { get; set; }
        public System.Guid ProcessInstanceId { get; set; }
        public string ProcessToken { get; set; }
        public string ClaimsIdentity { get; set; }
        public string FlowId { get; set; }
        public string SurveyKey { get; set; }
        public string InterfaceKey { get; set; }
        public System.DateTime CommencementDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
