//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIProcessInstanceParking_Log
    {
        public System.Guid Id { get; set; }
        public string StepInstanceId { get; set; }
        public string EntityType { get; set; }
        public string EntityId { get; set; }
        public string By { get; set; }
        public string At { get; set; }
        public System.DateTime On { get; set; }
        public string Outcome { get; set; }
    }
}
